Max/float53
dolthub/vitess pull request #49
Opened 2021-02-17 23:17 UTC by max-hoffman

adds support and tests for `FLOAT(prec)`, which will help with pandas table creation.

2021-02-18 17:23 UTC, zachmu approved these changes
LGTM but @Hydrocharged should confirm this is the correct semantics for the float type. He understands the types better than I do.

2021-02-18 19:15 UTC, Hydrocharged requested changes
`FLOAT(n, m)` is deprecated behavior, from pre-`DECIMAL` days, but we can still parse it. We should error on it in the engine though.

2021-02-18 19:15 UTC, Hydrocharged commented on go/vt/sqlparser/sql.y
> +| '(' INTEGRAL ')'
`float_length_opt` is a duplicate of `decimal_length_opt` with this, making the addition redundant, so we can use `decimal_length_opt` instead. It also allows `DOUBLE(n)`, which is not supported.

2021-02-19 00:04 UTC, max-hoffman commented on go/vt/sqlparser/sql.y
> +| FLOAT_TYPE float_length_opt
cool, i think I got it right this time. had to re-read the tutorial a few times, syntax was a bit perplexing yesterday

2021-02-19 00:05 UTC, max-hoffman commented
> We should error on it in the engine though.

@Hydrocharged What do you mean by this? I saw the deprecation in the mysql docs, but I need it to not error in practice

2021-02-19 00:26 UTC, Hydrocharged commented
> 
> 
> > We should error on it in the engine though.
> 
> @Hydrocharged What do you mean by this? I saw the deprecation in the mysql docs, but I need it to not error in practice

Do we need `FLOAT(n)` functionality only? Or we need `FLOAT(n, m)` as well? I was only speaking to `FLOAT(n, m)` regarding the error.

2021-02-19 00:28 UTC, max-hoffman commented
Ok got it, do you have any suggestions for implementing that other than of defining a separate `length_op`?

2021-02-19 00:38 UTC, Hydrocharged approved these changes
Covered it all in a quick chat so we're good to go!

2021-02-25 03:05 UTC, merged